---
title: "Wikipedia Article Views & Google Search Intensity"
author: "Ondrej Pekacek/TI CZ"
date: "Last updated `r format (Sys.time(),'%d. %m. %Y')`"
output: 
  flexdashboard::flex_dashboard:
    logo: "data/logo_ti.png"
    theme: cosmo
    orientation: columns
    vertical_layout: fill
    source_code: https://github.com/opop999/election_monitoring_wiki_popularity
    navbar:
      - {title: "About Project", icon: "ion-information-circled", href: "https://www.transparentnivolby.cz/snemovna2021"}
      - {title: "About Author", icon: "ion-social-linkedin", href: "https://www.linkedin.com/in/ondrej-pekacek"}
      - {title: "Data: Google", icon: "ion-cloud", href: "https://trends.google.com/"}
      - {title: "Data: Wikipedia", icon: "ion-cloud", href: "https://www.mediawiki.org/wiki/API:Main_page"}
      
---

```{r setup, include=FALSE}
# Disable scientific notation of numbers
options(scipen = 999)

# Package names
packages <- c("flexdashboard", "dplyr", "ggplot2", "plotly", "forcats", "htmlwidgets", "stringr")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

# Specify output directory for individual plots
directory <- "data/html_plots"

# Check whether output directory exists to save individual plots
if (!dir.exists(directory)) {
  dir.create(directory)
} else {
  print("Output directory already exists")
}

# Datasets loading
df_all_wiki <- readRDS(file = "data/full_data_wiki.rds")
df_all_gtrends <- readRDS(file = "data/full_data_gtrends.rds")

df_total_wiki <- readRDS(file = "data/summary_tables/total_views_summary_wiki.rds")
df_total_gtrends <- readRDS(file = "data/summary_tables/total_views_summary_gtrends.rds")

df_per_year_wiki <- readRDS(file = "data/summary_tables/per_year_views_summary_wiki.rds")
df_per_year_gtrends <- readRDS(file = "data/summary_tables/per_year_views_summary_gtrends.rds")

# Election date for vertical line in the time-plots
election_date <- as.Date("2021-10-08")

# Graph zoom date end & beginning
start_date <- as.Date("2015-07-01")
end_date <- as.Date("2021-12-31")

```

Total
=====================================

Column
-----------------------------------------------------------------------

### Chart Wiki Total

```{r}
plot_total_views_wiki <- ggplotly(
  df_total_wiki %>%
    mutate(
      entity_name = reorder(entity_name, total_views),
      total_views_thousand = round(total_views / 1000, digits = 0)
    ) %>%
    ggplot(aes(x = total_views_thousand, y = entity_name)) +
    geom_col(fill = "#db1d0b") +
    scale_x_continuous(
      breaks = seq(0, 10000, 50),
      labels = seq(0, 10000, 50)
    ) +
    scale_y_discrete(labels = (levels(reorder(df_total_wiki$entity_name, df_total_wiki$total_views)) %>%
      str_replace_all(pattern = "_", replacement = " ") %>%
      str_to_title())) +
    theme_minimal() +
    xlab(element_blank()) +
    ylab(element_blank()) +
    ggtitle(paste("Total views (in thousands) of Wikipedia articles since", format(start_date, "%d.%m.%Y")))
)

plot_total_views_wiki

saveWidget(plot_total_views_wiki, file = paste0(directory, "/plot_total_views_wiki.html"))

```

Column
-----------------------------------------------------------------------

### Chart Gtrends Total

```{r}
plot_total_views_gtrends <- ggplotly(
  df_total_gtrends %>%
    mutate(entity_name = reorder(entity_name, total_hits)) %>%
    ggplot(aes(x = total_hits, y = entity_name)) +
    geom_col(fill = "#03457f") +
    scale_x_continuous(
      breaks = seq(0, 10000, 100),
      labels = seq(0, 10000, 100)
    ) +
    theme_minimal() +
    xlab(element_blank()) +
    ylab(element_blank()) +
    ggtitle(paste("Cumulative intensity of Google searches since", format(start_date, "%d.%m.%Y")))
)

plot_total_views_gtrends

saveWidget(plot_total_views_wiki, file = paste0(directory, "/plot_total_views_gtrends.html"))

```

Per Year
=====================================

Column 
-----------------------------------------------------------------------

### Chart Wiki Per Year

```{r}
plot_views_yearly_wiki <- ggplotly(
  df_per_year_wiki %>%
    mutate(entity_name = reorder(entity_name, desc(entity_name)),
      total_views_thousand = round(total_views / 1000, digits = 0)
    ) %>%
    ggplot(aes(x = total_views_thousand, y = entity_name)) +
    geom_col(fill = "#0b92db") +
    scale_x_continuous(
      breaks = seq(0, 200, 25),
      labels = seq(0, 200, 25)
    ) +
     scale_y_discrete(labels = (levels(reorder(df_per_year_wiki$entity_name, desc(df_per_year_wiki$entity_name))) %>%
      str_replace_all(pattern = "_", replacement = " ") %>%
      str_to_title())) +
    theme_minimal() +
    theme(
      panel.border = element_rect(colour = "black", fill = NA, size = 0.5),
      panel.spacing.x = unit(0.5, "line"),
      strip.background = element_rect(fill = "grey")
    ) +
    facet_grid(cols = vars(year)) +
    xlab(element_blank()) +
    ylab(element_blank()) +
    ggtitle(paste("Views (in thousands) of Wikipedia articles per year since", format(start_date, "%d.%m.%Y")))
)

plot_views_yearly_wiki

saveWidget(plot_total_views_wiki, file = paste0(directory, "/plot_views_yearly_wiki.html"))
```

Column 
-----------------------------------------------------------------------

### Chart Gtrends Per Year

```{r}
plot_views_yearly_gtrends <- ggplotly(
  df_per_year_gtrends %>%
    mutate(entity_name = reorder(entity_name, desc(entity_name))) %>%
    ggplot(aes(x = total_hits, y = entity_name)) +
    geom_col(fill = "#50db0b") +
    scale_x_continuous(
      breaks = seq(0, 1000, 100),
      labels = seq(0, 1000, 100)
    ) +
    theme_minimal() +
    theme(
      panel.border = element_rect(colour = "black", fill = NA, size = 0.5),
      panel.spacing.x = unit(0.5, "line"),
      strip.background = element_rect(fill = "grey")
    ) +
    facet_grid(cols = vars(year)) +
    xlab(element_blank()) +
    ylab(element_blank()) +
    ggtitle(paste("Relative intensity of Google searches per year since", format(start_date, "%d.%m.%Y")))
)

plot_views_yearly_gtrends

saveWidget(plot_total_views_gtrends, file = paste0(directory, "/plot_views_yearly_gtrends.html"))
```

Throughout Time
=====================================

Column 
-----------------------------------------------------------------------

### Chart Time-Series Wiki

```{r}
views_over_time_wiki <- ggplotly(
  df_all_wiki %>%
    arrange(date) %>%
    group_by(entity_name) %>%
    mutate(cumulative_views_thousand = round(cumsum(views) / 1000, digits = 1)) %>%
    ungroup() %>% 
    ggplot(aes(x = as.Date(date), y = cumulative_views_thousand, color = entity_name)) +
    geom_line() +
    geom_vline(aes(xintercept = as.numeric(election_date)), color = "#db1d0b") +
    geom_text(aes(x = election_date, y = 0, label = "elections"), color = "#03457f", size = 4, angle = 90, vjust = -0.4, hjust = 0) +
    theme_minimal() +
    scale_y_continuous(
      breaks = seq(0, 500, 50),
      labels = seq(0, 500, 50)
    ) +
    scale_x_date(date_breaks = "1 years", date_labels = "%Y") +
    coord_cartesian(xlim = c(start_date, end_date)) +
    theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1)) +
    xlab(element_blank()) +
    ylab(element_blank()) +
    ggtitle(paste("Views (in thousands) of Wikipedia articles since", format(start_date, "%d.%m.%Y")))
)

views_over_time_wiki

saveWidget(views_over_time_wiki, file = paste0(directory, "/views_over_time_wiki.html"))

```

Column 
-----------------------------------------------------------------------

### Chart Time-Series Gtrends

```{r}
views_over_time_gtrends <- ggplotly(
  df_all_gtrends %>%
    arrange(date) %>%
    group_by(entity_name) %>%
    mutate(cumulative_hits = cumsum(hits)) %>%
    ungroup() %>% 
    ggplot(aes(x = as.Date(date), y = cumulative_hits, color = entity_name)) +
    geom_line() +
    geom_vline(aes(xintercept = as.numeric(election_date)), color = "#db1d0b") +
    geom_text(aes(x = election_date, y = 0, label = "elections"), color = "#03457f", size = 4, angle = 90, vjust = -0.4, hjust = 0) +
    theme_minimal() +
    scale_y_continuous(
      breaks = seq(0, 1000, 100),
      labels = seq(0, 1000, 100)
    ) +
    scale_x_date(date_breaks = "1 years", date_labels = "%Y") +
    coord_cartesian(xlim = c(start_date, end_date)) +
    theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1)) +
    xlab(element_blank()) +
    ylab(element_blank()) +
    ggtitle(paste("Relative intensity of Google searches since", format(start_date, "%d.%m.%Y")))
)

views_over_time_gtrends

saveWidget(views_over_time_gtrends, file = paste0(directory, "/views_over_time_gtrends.html"))

```

```{r cleanup, include=FALSE}
# Because the saveWidget function does not correctly delete the dependency files
# which are used to create individual self-sustaining widgets, we have to delete
# them using R functions. All non-html files in output folder are deleted.

unlink(grep(
  x = list.files(
    path = directory,
    recursive = TRUE,
    include.dirs = TRUE,
    full.names = TRUE
  ),
  pattern = "(.html)$",
  invert = TRUE,
  value = TRUE
))

```
